# Automatically generated by macro, please don't touch.

proc newUser*(node534638: JsonNode): User {.inline.} =
  result = node534638.to(User)

proc newOverwrite*(node535998: JsonNode): Overwrite {.inline.} =
  result = node535998.to(Overwrite)

proc newChannel*(node536281: JsonNode): Channel {.inline.} =
  result = node536281.to(Channel)

proc newEmbedFooter*(node539476: JsonNode): EmbedFooter {.inline.} =
  result = node539476.to(EmbedFooter)

proc newEmbedImage*(node539780: JsonNode): EmbedImage {.inline.} =
  result = node539780.to(EmbedImage)

proc newEmbedThumbnail*(node540189: JsonNode): EmbedThumbnail {.inline.} =
  result = node540189.to(EmbedThumbnail)

proc newEmbedVideo*(node540598: JsonNode): EmbedVideo {.inline.} =
  result = node540598.to(EmbedVideo)

proc newEmbedProvider*(node540920: JsonNode): EmbedProvider {.inline.} =
  result = node540920.to(EmbedProvider)

proc newEmbedAuthor*(node541169: JsonNode): EmbedAuthor {.inline.} =
  result = node541169.to(EmbedAuthor)

proc newEmbedField*(node541592: JsonNode): EmbedField {.inline.} =
  result = node541592.to(EmbedField)

proc newEmbed*(node541857: JsonNode): Embed {.inline.} =
  result = node541857.to(Embed)

proc newAttachment*(node545969: JsonNode): Attachment {.inline.} =
  result = node545969.to(Attachment)

proc newMessageActivity*(node546475: JsonNode): MessageActivity {.inline.} =
  result = node546475.to(MessageActivity)

proc newMessageApplication*(node546984: JsonNode): MessageApplication {.inline.} =
  result = node546984.to(MessageApplication)

proc newEmoji*(node547337: JsonNode): Emoji {.inline.} =
  result = node547337.to(Emoji)

proc newReaction*(node549171: JsonNode): Reaction {.inline.} =
  result = node549171.to(Reaction)

proc newMessage*(node550741: JsonNode): Message {.inline.} =
  result = node550741.to(Message)

proc newGame*(node561820: JsonNode): Game {.inline.} =
  result = node561820.to(Game)

proc newPresence*(node562054: JsonNode): Presence {.inline.} =
  result = node562054.to(Presence)

proc newRole*(node562489: JsonNode): Role {.inline.} =
  result = node562489.to(Role)

proc newGuildMember*(node562965: JsonNode): GuildMember {.inline.} =
  result = node562965.to(GuildMember)

proc newVoiceState*(node564212: JsonNode): VoiceState {.inline.} =
  result = node564212.to(VoiceState)

proc newVoiceRegion*(node566081: JsonNode): VoiceRegion {.inline.} =
  result = node566081.to(VoiceRegion)

proc newGuild*(node566458: JsonNode): Guild {.inline.} =
  result = node566458.to(Guild)

proc newIntegrationAccount*(node577605: JsonNode): IntegrationAccount {.inline.} =
  result = node577605.to(IntegrationAccount)

proc newInviteGuild*(node577790: JsonNode): InviteGuild {.inline.} =
  result = node577790.to(InviteGuild)

proc newInviteChannel*(node578087: JsonNode): InviteChannel {.inline.} =
  result = node578087.to(InviteChannel)

proc newInvite*(node578321: JsonNode): Invite {.inline.} =
  result = node578321.to(Invite)

proc newInviteMetadata*(node579386: JsonNode): InviteMetadata {.inline.} =
  result = node579386.to(InviteMetadata)

proc newUserGuild*(node580484: JsonNode): UserGuild {.inline.} =
  result = node580484.to(UserGuild)

proc newIntegration*(node580822: JsonNode): Integration {.inline.} =
  result = node580822.to(Integration)

proc newConnection*(node582255: JsonNode): Connection {.inline.} =
  result = node582255.to(Connection)

proc newWebhook*(node584073: JsonNode): Webhook {.inline.} =
  result = node584073.to(Webhook)

proc newChannelParams*(node585334: JsonNode): ChannelParams {.inline.} =
  result = node585334.to(ChannelParams)

proc newGuildParams*(node586174: JsonNode): GuildParams {.inline.} =
  result = node586174.to(GuildParams)

proc newGuildMemberParams*(node586730: JsonNode): GuildMemberParams {.inline.} =
  result = node586730.to(GuildMemberParams)

proc newGuildEmbed*(node587164: JsonNode): GuildEmbed {.inline.} =
  result = node587164.to(GuildEmbed)

proc newWebhookParams*(node587373: JsonNode): WebhookParams {.inline.} =
  result = node587373.to(WebhookParams)

proc newGuildEmojisUpdate*(node591016: JsonNode): GuildEmojisUpdate {.inline.} =
  result = node591016.to(GuildEmojisUpdate)

proc newGuildIntegrationsUpdate*(node592666: JsonNode): GuildIntegrationsUpdate {.
    inline.} =
  result = node592666.to(GuildIntegrationsUpdate)

proc newGuildRoleCreate*(node592795: JsonNode): GuildRoleCreate {.inline.} =
  result = node592795.to(GuildRoleCreate)

proc newGuildRoleUpdate*(node593375: JsonNode): GuildRoleUpdate {.inline.} =
  result = node593375.to(GuildRoleUpdate)

proc newGuildRoleDelete*(node593955: JsonNode): GuildRoleDelete {.inline.} =
  result = node593955.to(GuildRoleDelete)

proc newAuditLogOptions*(node594140: JsonNode): AuditLogOptions {.inline.} =
  result = node594140.to(AuditLogOptions)

proc newMessageDeleteBulk*(node594605: JsonNode): MessageDeleteBulk {.inline.} =
  result = node594605.to(MessageDeleteBulk)

proc newPresenceUpdate*(node594943: JsonNode): PresenceUpdate {.inline.} =
  result = node594943.to(PresenceUpdate)

proc newTypingStart*(node596272: JsonNode): TypingStart {.inline.} =
  result = node596272.to(TypingStart)

proc newVoiceServerUpdate*(node596562: JsonNode): VoiceServerUpdate {.inline.} =
  result = node596562.to(VoiceServerUpdate)

proc newResumed*(node596803: JsonNode): Resumed {.inline.} =
  result = node596803.to(Resumed)

proc newMessageCreate*(node597029: JsonNode): MessageCreate {.inline.} =
  result = node597029.to(MessageCreate)

proc newMessageUpdate*(node607020: JsonNode): MessageUpdate {.inline.} =
  result = node607020.to(MessageUpdate)

proc newMessageDelete*(node617011: JsonNode): MessageDelete {.inline.} =
  result = node617011.to(MessageDelete)

proc newGuildMemberAdd*(node627002: JsonNode): GuildMemberAdd {.inline.} =
  result = node627002.to(GuildMemberAdd)

proc newGuildMemberUpdate*(node628249: JsonNode): GuildMemberUpdate {.inline.} =
  result = node628249.to(GuildMemberUpdate)

proc newGuildMemberRemove*(node629496: JsonNode): GuildMemberRemove {.inline.} =
  result = node629496.to(GuildMemberRemove)

proc newGuildMembersChunk*(node630743: JsonNode): GuildMembersChunk {.inline.} =
  result = node630743.to(GuildMembersChunk)

proc newGuildCreate*(node632220: JsonNode): GuildCreate {.inline.} =
  result = node632220.to(GuildCreate)

proc newGuildUpdate*(node642961: JsonNode): GuildUpdate {.inline.} =
  result = node642961.to(GuildUpdate)

proc newGuildDelete*(node653702: JsonNode): GuildDelete {.inline.} =
  result = node653702.to(GuildDelete)

proc newGuildBanAdd*(node653879: JsonNode): GuildBanAdd {.inline.} =
  result = node653879.to(GuildBanAdd)

proc newGuildBanRemove*(node654618: JsonNode): GuildBanRemove {.inline.} =
  result = node654618.to(GuildBanRemove)

proc newChannelCreate*(node655357: JsonNode): ChannelCreate {.inline.} =
  result = node655357.to(ChannelCreate)

proc newChannelUpdate*(node657943: JsonNode): ChannelUpdate {.inline.} =
  result = node657943.to(ChannelUpdate)

proc newChannelDelete*(node660529: JsonNode): ChannelDelete {.inline.} =
  result = node660529.to(ChannelDelete)

proc newPin*(node663115: JsonNode): Pin {.inline.} =
  result = node663115.to(Pin)

proc newChannelPinsUpdate*(node663300: JsonNode): ChannelPinsUpdate {.inline.} =
  result = node663300.to(ChannelPinsUpdate)

proc newUserUpdate*(node663485: JsonNode): UserUpdate {.inline.} =
  result = node663485.to(UserUpdate)

proc newVoiceStateUpdate*(node664224: JsonNode): VoiceStateUpdate {.inline.} =
  result = node664224.to(VoiceStateUpdate)

proc newMessageReactionRemove*(node666093: JsonNode): MessageReactionRemove {.inline.} =
  result = node666093.to(MessageReactionRemove)

proc newWebhooksUpdate*(node667790: JsonNode): WebhooksUpdate {.inline.} =
  result = node667790.to(WebhooksUpdate)

proc newMessageReactionAdd*(node669051: JsonNode): MessageReactionAdd {.inline.} =
  result = node669051.to(MessageReactionAdd)

proc newMessageReactionRemoveAll*(node670748: JsonNode): MessageReactionRemoveAll {.
    inline.} =
  result = node670748.to(MessageReactionRemoveAll)

proc newReady*(node670989: JsonNode): Ready {.inline.} =
  result = node670989.to(Ready)